# Generated by Django 5.1.3 on 2024-11-06 12:00

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.fields.StreamField([('product_details', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Enter the product title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Provide a description of the product'}), 2: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Select Category page', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Enter the price'}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Upload or select an image for the product'}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add tags to describe the product'}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.StructBlock', [[('main_title', 0), ('description', 1), ('category', 2), ('available_size', 4), ('images', 6), ('tags', 8)]], {})})),
            ],
            options={
                'verbose_name': 'Product Page',
                'verbose_name_plural': 'Product Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
