# Generated by Django 5.1.3 on 2024-11-06 19:32

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='content',
            field=wagtail.fields.StreamField([('product_details', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Enter the product title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Provide a description of the product'}), 2: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Select Category page', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Enter the Size'}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Upload or select an image for the product'}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add tags to describe the product'}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.StructBlock', [[('main_title', 0), ('description', 1), ('category', 2), ('available_size', 4), ('images', 6), ('tags', 8)]], {})}),
        ),
    ]
